#
# MPowerTCX: Share Schwinn A.C. indoor cycle data with Strava, GoldenCheetah 
# and other apps.
#
# Copyright (C) 2016-2017 James Roth
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(680, 458)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setMargin(12)
        self.gridLayout_3.setHorizontalSpacing(16)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(320, 160))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(16)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setVerticalSpacing(8)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelWorkoutTime = QtGui.QLabel(self.groupBox)
        self.labelWorkoutTime.setObjectName(_fromUtf8("labelWorkoutTime"))
        self.gridLayout.addWidget(self.labelWorkoutTime, 0, 0, 1, 1)
        self.workoutTime = QtGui.QDateTimeEdit(self.groupBox)
        self.workoutTime.setObjectName(_fromUtf8("workoutTime"))
        self.gridLayout.addWidget(self.workoutTime, 0, 1, 1, 1)
        self.labelPowerAdjustment = QtGui.QLabel(self.groupBox)
        self.labelPowerAdjustment.setObjectName(_fromUtf8("labelPowerAdjustment"))
        self.gridLayout.addWidget(self.labelPowerAdjustment, 2, 0, 1, 1)
        self.powerAdjustment = QtGui.QDoubleSpinBox(self.groupBox)
        self.powerAdjustment.setMinimum(-100.0)
        self.powerAdjustment.setMaximum(100.0)
        self.powerAdjustment.setSingleStep(0.1)
        self.powerAdjustment.setObjectName(_fromUtf8("powerAdjustment"))
        self.gridLayout.addWidget(self.powerAdjustment, 2, 1, 1, 1)
        self.useFileDate = QtGui.QCheckBox(self.groupBox)
        self.useFileDate.setObjectName(_fromUtf8("useFileDate"))
        self.gridLayout.addWidget(self.useFileDate, 1, 0, 1, 2)
        self.checkBoxExtra = QtGui.QCheckBox(self.groupBox)
        self.checkBoxExtra.setObjectName(_fromUtf8("checkBoxExtra"))
        self.gridLayout.addWidget(self.checkBoxExtra, 3, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(320, 160))
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setMargin(16)
        self.gridLayout_2.setHorizontalSpacing(12)
        self.gridLayout_2.setVerticalSpacing(8)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelDurationName = QtGui.QLabel(self.groupBox_2)
        self.labelDurationName.setObjectName(_fromUtf8("labelDurationName"))
        self.gridLayout_2.addWidget(self.labelDurationName, 1, 0, 1, 1)
        self.labelDuration = QtGui.QLabel(self.groupBox_2)
        self.labelDuration.setText(_fromUtf8(""))
        self.labelDuration.setObjectName(_fromUtf8("labelDuration"))
        self.gridLayout_2.addWidget(self.labelDuration, 1, 1, 1, 1)
        self.labelAveragePowerName = QtGui.QLabel(self.groupBox_2)
        self.labelAveragePowerName.setObjectName(_fromUtf8("labelAveragePowerName"))
        self.gridLayout_2.addWidget(self.labelAveragePowerName, 2, 0, 1, 1)
        self.labelAveragePower = QtGui.QLabel(self.groupBox_2)
        self.labelAveragePower.setText(_fromUtf8(""))
        self.labelAveragePower.setObjectName(_fromUtf8("labelAveragePower"))
        self.gridLayout_2.addWidget(self.labelAveragePower, 2, 1, 1, 1)
        self.labelMaxPowerName = QtGui.QLabel(self.groupBox_2)
        self.labelMaxPowerName.setObjectName(_fromUtf8("labelMaxPowerName"))
        self.gridLayout_2.addWidget(self.labelMaxPowerName, 3, 0, 1, 1)
        self.labelMaxPower = QtGui.QLabel(self.groupBox_2)
        self.labelMaxPower.setText(_fromUtf8(""))
        self.labelMaxPower.setObjectName(_fromUtf8("labelMaxPower"))
        self.gridLayout_2.addWidget(self.labelMaxPower, 3, 1, 1, 1)
        self.labelEquipmentName = QtGui.QLabel(self.groupBox_2)
        self.labelEquipmentName.setObjectName(_fromUtf8("labelEquipmentName"))
        self.gridLayout_2.addWidget(self.labelEquipmentName, 0, 0, 1, 1)
        self.labelEquipment = QtGui.QLabel(self.groupBox_2)
        self.labelEquipment.setText(_fromUtf8(""))
        self.labelEquipment.setObjectName(_fromUtf8("labelEquipment"))
        self.gridLayout_2.addWidget(self.labelEquipment, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBoxPhysics = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxPhysics.setMinimumSize(QtCore.QSize(320, 160))
        self.groupBoxPhysics.setFlat(True)
        self.groupBoxPhysics.setObjectName(_fromUtf8("groupBoxPhysics"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxPhysics)
        self.gridLayout_5.setMargin(16)
        self.gridLayout_5.setHorizontalSpacing(12)
        self.gridLayout_5.setVerticalSpacing(8)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.groupBoxPhysics)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.doubleSpinBoxRiderWeight = QtGui.QDoubleSpinBox(self.groupBoxPhysics)
        self.doubleSpinBoxRiderWeight.setDecimals(1)
        self.doubleSpinBoxRiderWeight.setMaximum(1000.0)
        self.doubleSpinBoxRiderWeight.setProperty("value", 70.0)
        self.doubleSpinBoxRiderWeight.setObjectName(_fromUtf8("doubleSpinBoxRiderWeight"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxRiderWeight, 1, 1, 1, 1)
        self.comboBoxUnits = QtGui.QComboBox(self.groupBoxPhysics)
        self.comboBoxUnits.setObjectName(_fromUtf8("comboBoxUnits"))
        self.comboBoxUnits.addItem(_fromUtf8(""))
        self.comboBoxUnits.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBoxUnits, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBoxPhysics)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 2, 0, 1, 1)
        self.doubleSpinBoxBikeWeight = QtGui.QDoubleSpinBox(self.groupBoxPhysics)
        self.doubleSpinBoxBikeWeight.setDecimals(1)
        self.doubleSpinBoxBikeWeight.setMaximum(1000.0)
        self.doubleSpinBoxBikeWeight.setProperty("value", 8.0)
        self.doubleSpinBoxBikeWeight.setObjectName(_fromUtf8("doubleSpinBoxBikeWeight"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxBikeWeight, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 3, 0, 1, 1)
        self.checkBoxPhysics = QtGui.QCheckBox(self.groupBoxPhysics)
        self.checkBoxPhysics.setObjectName(_fromUtf8("checkBoxPhysics"))
        self.gridLayout_5.addWidget(self.checkBoxPhysics, 0, 0, 1, 3)
        self.gridLayout_3.addWidget(self.groupBoxPhysics, 1, 0, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(16, 20, 16, 16)
        self.gridLayout_4.setHorizontalSpacing(16)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.saveButton = QtGui.QPushButton(self.widget)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 32))
        self.saveButton.setStyleSheet(_fromUtf8(""))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.gridLayout_4.addWidget(self.saveButton, 1, 1, 1, 1)
        self.loadButton = QtGui.QPushButton(self.widget)
        self.loadButton.setMinimumSize(QtCore.QSize(0, 32))
        self.loadButton.setStyleSheet(_fromUtf8(""))
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.gridLayout_4.addWidget(self.loadButton, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 2, 0, 1, 2)
        self.groupBoxCompatibility = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxCompatibility.setMinimumSize(QtCore.QSize(320, 160))
        self.groupBoxCompatibility.setFlat(True)
        self.groupBoxCompatibility.setObjectName(_fromUtf8("groupBoxCompatibility"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxCompatibility)
        self.gridLayout_6.setMargin(16)
        self.gridLayout_6.setHorizontalSpacing(12)
        self.gridLayout_6.setVerticalSpacing(8)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.checkBoxInterpolate = QtGui.QCheckBox(self.groupBoxCompatibility)
        self.checkBoxInterpolate.setChecked(True)
        self.checkBoxInterpolate.setObjectName(_fromUtf8("checkBoxInterpolate"))
        self.gridLayout_6.addWidget(self.checkBoxInterpolate, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBoxCompatibility, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MPowerTCX", None))
        self.groupBox.setTitle(_translate("MainWindow", "Options", None))
        self.labelWorkoutTime.setText(_translate("MainWindow", "Workout Time:", None))
        self.labelPowerAdjustment.setText(_translate("MainWindow", "Power Adjustment:", None))
        self.powerAdjustment.setSuffix(_translate("MainWindow", "%", None))
        self.useFileDate.setText(_translate("MainWindow", "Use File Time as Workout Time", None))
        self.checkBoxExtra.setText(_translate("MainWindow", "Show Extra Options", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Workout Info", None))
        self.labelDurationName.setText(_translate("MainWindow", "Duration:", None))
        self.labelAveragePowerName.setText(_translate("MainWindow", "Average Power:", None))
        self.labelMaxPowerName.setText(_translate("MainWindow", "Max Power:", None))
        self.labelEquipmentName.setText(_translate("MainWindow", "Equipment:", None))
        self.groupBoxPhysics.setTitle(_translate("MainWindow", "Physics", None))
        self.label.setText(_translate("MainWindow", "Rider Weight:", None))
        self.comboBoxUnits.setItemText(0, _translate("MainWindow", "kg", None))
        self.comboBoxUnits.setItemText(1, _translate("MainWindow", "lbs", None))
        self.label_2.setText(_translate("MainWindow", "Bike Weight:", None))
        self.checkBoxPhysics.setText(_translate("MainWindow", "Recalculate Speed and Distance", None))
        self.saveButton.setText(_translate("MainWindow", "Save TCX...", None))
        self.loadButton.setText(_translate("MainWindow", "Load CSV...", None))
        self.groupBoxCompatibility.setTitle(_translate("MainWindow", "Compatibility", None))
        self.checkBoxInterpolate.setText(_translate("MainWindow", "Interpolate", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))

from . import images_rc
