"""
This is a setup.py script generated by py2applet

Usage:
    python setup_py2app.py py2app
"""
import shutil
from setuptools import setup

shutil.copy('../images/mpowertcx icon flat.icns', 'dist')

APP = ['mpowertcx.py']
DATA_FILES = []
OPTIONS = {'packages': 'PySide2',
           'iconfile': 'dist/mpowertcx icon flat.icns',
           'frameworks': [
               '/Users/user/miniconda3/lib/python3.7/site-packages/shiboken2/libshiboken2.abi3.5.12.dylib',
               '/Users/user/miniconda3/pkgs/libffi-3.2.1-h475c297_4/lib/libffi.6.dylib'
           ]}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
